name: CI

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test and coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Install SDL2
        run: |
          sudo apt-get update -q
          sudo apt-get install -y libegl1-mesa-dev libgles2-mesa-dev libsdl2-dev

      - name: cargo test
        run: cargo test --verbose

      - uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate coverage report
        run: cargo llvm-cov --bin rust64 --summary-only
